# Generated by Django 3.1 on 2020-12-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SwapNGameOn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_category', to='SwapNGameOn.category'),
        ),
        migrations.AddField(
            model_name='game',
            name='imageLink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='swap',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
