# Generated by Django 3.1 on 2021-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwapNGameOn', '0003_auto_20210101_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='contactNumber',
            field=models.IntegerField(null=True),
        ),
    ]
