# Generated by Django 3.1 on 2021-01-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwapNGameOn', '0004_request_contactnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='isAccepted',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='processing', max_length=255),
        ),
    ]
