# Generated by Django 3.1 on 2021-01-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwapNGameOn', '0005_auto_20210103_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='altMeetup',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
