# Generated by Django 3.1 on 2021-01-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwapNGameOn', '0006_auto_20210104_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='imageLink',
            field=models.TextField(null=True),
        ),
    ]
